/* V6 BATCH 2.1 — Scout Negotiations Fix */
(function(){
"use strict";
function saveNow(){if(typeof save==="function")save();}
function fmt(n){return typeof money==="function"?money(n):"$"+Number(n||0).toFixed(1)+"m"}
window.scoutAccept=function(id){const o=(S.offers||[]).find(x=>x.id===id&&x.kind==="scout");if(!o)return;const p=(S.market||[]).find(x=>x.id===o.playerId)||(S.worldPool||[]).find(x=>x.id===o.playerId);if(!p||p.club!=="World Pool")return alert("This player is no longer available.");if(Number(o.amount)>Number(clubMoney(S.selected).budget||0))return alert("That exceeds your transfer budget.");S.players[S.selected]=S.players[S.selected]||[];if(S.players[S.selected].some(x=>x.id===p.id||x.name===p.name))return alert("Transfer blocked: duplicate player detected.");p.club=S.selected;S.players[S.selected].push(p);S.market=(S.market||[]).filter(x=>x.id!==p.id);S.worldPool=(S.worldPool||[]).filter(x=>x.id!==p.id);clubMoney(S.selected).budget=Math.max(0,clubMoney(S.selected).budget-Number(o.amount));S.offers=S.offers.filter(x=>x.id!==id);S.logs.unshift("TRANSFER COMPLETE: "+p.name+" joined "+S.selected+" for "+fmt(o.amount)+".");saveNow();alert(p.name+" joined "+S.selected+" for "+fmt(o.amount)+".");page("market")};
window.scoutReject=function(id){const o=(S.offers||[]).find(x=>x.id===id&&x.kind==="scout");if(!o)return;S.offers=S.offers.filter(x=>x.id!==id);S.logs.unshift("SCOUT NEGOTIATION: "+o.player+" offer rejected.");saveNow();page("market")};
window.scoutCounter=function(id){const o=(S.offers||[]).find(x=>x.id===id&&x.kind==="scout");if(!o)return;const current=Number(o.amount),raw=prompt("Counter-offer for "+o.player+" (millions):",current.toFixed(1));if(raw===null)return;const counter=Number(raw);if(!counter||counter<=current)return alert("Your counter must be higher than their current offer.");const asking=Number(o.asking||o.originalAsking||current);let response;if(counter>=asking&&Math.random()<0.68){o.amount=counter;o.status="accepted";saveNow();alert("The club accepted your counter-offer of "+fmt(counter)+".");return scoutAccept(id)}const gap=counter-current;response=+(Math.max(current,Math.min(counter,Math.max(asking,current)))+gap*(0.25+Math.random()*0.25)).toFixed(1);response=Math.max(current,Math.min(counter,response));o.amount=response;o.status="countered";o.lastUserOffer=counter;S.logs.unshift("SCOUT NEGOTIATION: "+o.player+" countered with "+fmt(response)+".");saveNow();alert("They countered with "+fmt(response)+".");page("market")};
window.makeOffer=function(id){const p=(S.market||[]).find(x=>x.id===id);if(!p)return;const asking=Number(p.asking||p.value||0),raw=prompt("Offer for "+p.name+" — asking "+fmt(asking),asking.toFixed(1));if(raw===null)return;const amount=Number(raw);if(!amount||amount<=0)return;if(amount>Number(clubMoney(S.selected).budget||0))return alert("That exceeds your transfer budget.");if(p.club!=="World Pool")return alert("This player is no longer available.");const ratio=amount/asking, chance=ratio>=1.15?.95:ratio>=1.05?.88:ratio>=1?.72:ratio>=.90?.42:.18;if(Math.random()<chance){const id2=uid();S.offers=S.offers||[];S.offers.push({id:id2,player:p.name,playerId:p.id,from:"World Pool",to:S.selected,amount,asking,originalAsking:asking,kind:"scout",status:"accepted"});return scoutAccept(id2)}const counter=amount>=asking?+(amount*(1.02+Math.random()*.06)).toFixed(1):+(Math.max(amount+.1,asking*(1.03+Math.random()*.10))).toFixed(1);S.offers=S.offers||[];S.offers.push({id:uid(),player:p.name,playerId:p.id,from:"World Pool",to:S.selected,amount:counter,asking,originalAsking:asking,previousOffer:amount,lastUserOffer:amount,kind:"scout",status:"countered"});S.logs.unshift("SCOUT NEGOTIATION: "+p.name+" countered with "+fmt(counter)+".");saveNow();alert("Counter-offer: "+fmt(counter));page("market")};
})();
